[package]
name = "modql"
version = "0.1.1-SNAPSHOT"
authors = ["Jeremy Chone <jeremy.chone@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Rust implementation for Model Query Language support"
categories = ["data-structures"]
keywords = [
	"query-language",
	"model",
	"data-model",
	"graphql"
]
homepage = "https://github.com/jeremychone/rust-modql"
repository = "https://github.com/jeremychone/rust-modql"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [".", "modql-macros"]


[dependencies]
modql-macros = { version="0.1.0", path = "modql-macros" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"


[dev-dependencies]
anyhow = "1"

