# rustfmt doc - https://rust-lang.github.io/rustfmt/

# JC Update 
hard_tabs = true
edition = "2021"
max_width = 120
chain_width = 80
array_width = 80

# imports_granularity = "Module" # no effect on rust analyzer
